<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <RootNamespace>Carpathia</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Product>ArtFusion</Product>
    <Company></Company>
    <Authors>GeniusPilot2016 (Nisa Özdoğan)</Authors>
    <Version>0.17.0-alpha</Version>
    <Title>ArtFusion</Title>
    <PackageId>artfusion</PackageId>
    <ApplicationIcon>artfusion_icon.ico</ApplicationIcon>
	<ForceDesignerDpiUnaware>true</ForceDesignerDpiUnaware>
    <SupportedOSPlatformVersion>10.0.17763.0</SupportedOSPlatformVersion>
    <Platforms>AnyCPU;x64</Platforms>
    <Year>$([System.DateTime]::Now.Year)</Year>
    <CopyrightYear Condition="'$(Year)' == '2025'">2025</CopyrightYear>
    <CopyrightYear Condition="'$(Year)' != '2025'">2025-$(Year)</CopyrightYear>
    <Copyright>© $(CopyrightYear) GeniusPilot2016. NeoBleeper is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="AIImageCreator.py" />
    <None Remove="AIImageEditor.py" />
  </ItemGroup>

  <ItemGroup>
	<Compile Remove="Datasets\**" />
	<EmbeddedResource Remove="Datasets\**" />
	<None Remove="Datasets\**" />  
    <Content Include="artfusion_icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="cmdwtf.BuildTimestampGenerator" Version="1.1.0" />
    <PackageReference Include="DirectShowLib" Version="1.0.0" />
    <PackageReference Include="Emgu.CV" Version="4.12.0.5764" />
    <PackageReference Include="Emgu.CV.Bitmap" Version="4.12.0.5764" />
    <PackageReference Include="Emgu.CV.runtime.windows" Version="4.12.0.5764" />
    <PackageReference Include="Emgu.CV.UI" Version="4.12.0.5764" />
    <PackageReference Include="ExifLibNet" Version="2.1.4" />
    <PackageReference Include="LLamaSharp" Version="0.25.0" />
    <PackageReference Include="MetadataExtractor" Version="2.9.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="System.Management" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="CryptographicSettings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>CryptographicSettings.settings</DependentUpon>
    </Compile>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Settings1.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings1.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="CryptographicSettings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>CryptographicSettings.Designer.cs</LastGenOutput>
    </None>
    <None Update="Resources\webcam_take_photo.wav">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Settings1.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings1.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>