<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows10.0.26100.0</TargetFramework>
    <RootNamespace>_222303026_proje3</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Product>ArtFusion</Product>
    <Company></Company>
    <Authors>Nisa Özdoğan</Authors>
    <Version>0.9.0</Version>
    <Title>ArtFusion</Title>
    <PackageId>artfusion</PackageId>
    <ApplicationIcon>artfusion_icon.ico</ApplicationIcon>
    <SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\webcam_take_photo.wav" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="artfusion_icon.ico" />
    <Content Include="Resources\webcam_take_photo.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DirectShowLib" Version="1.0.0" />
    <PackageReference Include="Emgu.CV" Version="4.10.0.5680" />
    <PackageReference Include="Emgu.CV.Bitmap" Version="4.10.0.5680" />
    <PackageReference Include="Emgu.CV.runtime.windows" Version="4.10.0.5680" />
    <PackageReference Include="Emgu.CV.UI" Version="4.10.0.5680" />
    <PackageReference Include="Google_GenerativeAI" Version="2.5.10" />
    <PackageReference Include="HuggingFace" Version="0.4.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.Management" Version="9.0.5" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="CryptographicSettings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>CryptographicSettings.settings</DependentUpon>
    </Compile>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Settings1.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings1.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="CryptographicSettings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>CryptographicSettings.Designer.cs</LastGenOutput>
    </None>
    <None Update="Settings1.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings1.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>