//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _222303026_proje3 {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0")]
    internal sealed partial class CryptographicSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static CryptographicSettings defaultInstance = ((CryptographicSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new CryptographicSettings())));
        
        public static CryptographicSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ohf3aR688kaRYSTu7lMeXPoSVUTFcS+WgraFY3mxda0=")]
        public string CipherKey1 {
            get {
                return ((string)(this["CipherKey1"]));
            }
            set {
                this["CipherKey1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TZnoSs4H8yQZ8kQTgZ7xwg==")]
        public string CipherIV1 {
            get {
                return ((string)(this["CipherIV1"]));
            }
            set {
                this["CipherIV1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ohf3aR688kaRYSTu7lMeXPoSVUTFcS+WgraFY3mxda0=")]
        public string CipherKey2 {
            get {
                return ((string)(this["CipherKey2"]));
            }
            set {
                this["CipherKey2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TZnoSs4H8yQZ8kQTgZ7xwg==")]
        public string CipherIV2 {
            get {
                return ((string)(this["CipherIV2"]));
            }
            set {
                this["CipherIV2"] = value;
            }
        }
    }
}
