//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carpathia.Properties {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Carpathia.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   System.Byte[] türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static byte[] HarmonyOS_Sans_Black {
            get {
                object obj = ResourceManager.GetObject("HarmonyOS_Sans_Black", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static byte[] HarmonyOS_Sans_Black_Italic {
            get {
                object obj = ResourceManager.GetObject("HarmonyOS_Sans_Black_Italic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static byte[] HarmonyOS_Sans_Bold {
            get {
                object obj = ResourceManager.GetObject("HarmonyOS_Sans_Bold", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static byte[] HarmonyOS_Sans_Bold_Italic {
            get {
                object obj = ResourceManager.GetObject("HarmonyOS_Sans_Bold_Italic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static byte[] HarmonyOS_Sans_Light {
            get {
                object obj = ResourceManager.GetObject("HarmonyOS_Sans_Light", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static byte[] HarmonyOS_Sans_Light_Italic {
            get {
                object obj = ResourceManager.GetObject("HarmonyOS_Sans_Light_Italic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static byte[] HarmonyOS_Sans_Medium {
            get {
                object obj = ResourceManager.GetObject("HarmonyOS_Sans_Medium", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static byte[] HarmonyOS_Sans_Medium_Italic {
            get {
                object obj = ResourceManager.GetObject("HarmonyOS_Sans_Medium_Italic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static byte[] HarmonyOS_Sans_Regular {
            get {
                object obj = ResourceManager.GetObject("HarmonyOS_Sans_Regular", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static byte[] HarmonyOS_Sans_Regular_Italic {
            get {
                object obj = ResourceManager.GetObject("HarmonyOS_Sans_Regular_Italic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static byte[] HarmonyOS_Sans_Thin {
            get {
                object obj = ResourceManager.GetObject("HarmonyOS_Sans_Thin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static byte[] HarmonyOS_Sans_Thin_Italic {
            get {
                object obj = ResourceManager.GetObject("HarmonyOS_Sans_Thin_Italic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_about_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-about-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_add_file_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-add-file-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_add_text_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-add-text-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_align_center_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-align-center-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_align_left_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-align-left-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_align_right_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-align-right-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_art_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-art-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_artificial_intelligence_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-artificial-intelligence-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_artificial_intelligence_481 {
            get {
                object obj = ResourceManager.GetObject("icons8-artificial-intelligence-481", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_background_remover_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-background-remover-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_black_and_white_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-black-and-white-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_blur_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-blur-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_blur_481 {
            get {
                object obj = ResourceManager.GetObject("icons8-blur-481", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_bold_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-bold-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_brush_48__1_ {
            get {
                object obj = ResourceManager.GetObject("icons8-brush-48 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_cartoon_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-cartoon-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_cherry_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-cherry-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_close_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-close-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_close_481 {
            get {
                object obj = ResourceManager.GetObject("icons8-close-481", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_color_dropper_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-color-dropper-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_copy_to_clipboard_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-copy-to-clipboard-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_copy_to_clipboard_481 {
            get {
                object obj = ResourceManager.GetObject("icons8-copy-to-clipboard-481", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_cursor_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-cursor-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_cut_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-cut-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_cut_481 {
            get {
                object obj = ResourceManager.GetObject("icons8-cut-481", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_dimension_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-dimension-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_dimension_96 {
            get {
                object obj = ResourceManager.GetObject("icons8-dimension-96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_diversity_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-diversity-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_done_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-done-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_done_481 {
            get {
                object obj = ResourceManager.GetObject("icons8-done-481", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_erase_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-erase-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_eraser_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-eraser-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_error_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-error-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_flash_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-flash-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_fog_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-fog-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_help_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-help-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_hexagon_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-hexagon-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_icy_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-icy-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_image_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-image-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_information_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-information-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_italic_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-italic-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_landscape_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-landscape-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_lavender_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-lavender-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_light_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-light-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_line_48__1_ {
            get {
                object obj = ResourceManager.GetObject("icons8-line-48 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_lipstick_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-lipstick-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_magic_wand_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-magic-wand-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_magnifier_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-magnifier-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_old_fashioned_family_photo_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-old-fashioned-family-photo-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_open_file_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-open-file-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_paint_bucket_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-paint-bucket-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_paint_sprayer_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-paint-sprayer-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_paste_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-paste-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_paste_481 {
            get {
                object obj = ResourceManager.GetObject("icons8-paste-481", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_pencil_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-pencil-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_photo_gallery_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-photo-gallery-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_pixel_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-pixel-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_print_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-print-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_question_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-question-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_rectangular_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-rectangular-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_redo_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-redo-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_redo_481 {
            get {
                object obj = ResourceManager.GetObject("icons8-redo-481", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_reflection_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-reflection-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_round_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-round-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_rounded_rectangle_stroked_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-rounded-rectangle-stroked-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_save_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-save-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_select_none_48__1_ {
            get {
                object obj = ResourceManager.GetObject("icons8-select-none-48 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_sheet_of_paper_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-sheet-of-paper-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_spa_candle_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-spa-candle-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_strikethrough_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-strikethrough-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_triangle_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-triangle-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_underline_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-underline-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_undo_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-undo-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_van_gogh_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-van-gogh-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_view_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-view-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_warning_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-warning-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_webcam_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-webcam-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_webcam_481 {
            get {
                object obj = ResourceManager.GetObject("icons8-webcam-481", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_winter_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-winter-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_zoom_in_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-zoom-in-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_zoom_out_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-zoom-out-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap librecanvas_icon {
            get {
                object obj = ResourceManager.GetObject("librecanvas_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap librecanvas_pattern {
            get {
                object obj = ResourceManager.GetObject("librecanvas_pattern", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap librecanvas_splash_background {
            get {
                object obj = ResourceManager.GetObject("librecanvas_splash_background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap pexels_dreamypixel_547115 {
            get {
                object obj = ResourceManager.GetObject("pexels-dreamypixel-547115", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap splash {
            get {
                object obj = ResourceManager.GetObject("splash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap toolstrip_dark {
            get {
                object obj = ResourceManager.GetObject("toolstrip_dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap toolstrip_light {
            get {
                object obj = ResourceManager.GetObject("toolstrip_light", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap transparent_pattern {
            get {
                object obj = ResourceManager.GetObject("transparent_pattern", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static byte[] webcam_take_photo {
            get {
                object obj = ResourceManager.GetObject("webcam_take_photo", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
